{% set name = "uravu" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uravu-{{ version }}.tar.gz
  sha256: 339afdf48e35d47c5c794d08af3e6e0cba217a005fc968c6ccd5959da22b28c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - numpy
    - scipy >=1.5.4
    - emcee
    - tqdm
    - uncertainties
    - dynesty
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy >=1.5.4
    - emcee
    - tqdm
    - uncertainties
    - dynesty

test:
  imports:
    - uravu
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/arm61/uravu
  summary: Bayesian methods for analytical relationships
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
